# -*- coding: utf-8 -*-
"""Activity 6_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7QU6hLqVznm-rJMc0ufW7Ujx6sacV_B

# Activity 6.1: Refactoring a Previous Lab Assignment

# LAB2_1 Refactoring

##example
"""

num = input("input your number : ")

def check(input_num):

  try:
    num_int = int(input_num)
    print(f"Your type : {type(num_int)}")
    return 0

  except ValueError:
    print(f"Your type : {type(input_num)}")
    print("Your input is not a integer number")
    return 1

def number(number):
  ch = check(number)
  if ch == 0:
    num = int(number)
    if num < 0:
      print("Your number < 0")
    elif num > 0:
      print("Your number > 0")
    else:
      print("Your number = 0")
    print("--------------------------------------------------")
    if (num%2) == 0:
      print("Your number is even number")
    else:
      print("Your number is odd number")

number(num)

"""##result"""

num = input("input your number : ")

def check_number(num):
  if num < 0:
    print("Your number < 0")
  elif num > 0:
    print("Your number > 0")
  else:
   print("Your number = 0")
  print("--------------------------------------------------")

def check_even_odd(num):
  if (num%2) == 0:
    print("Your number is even number")
  else:
    print("Your number is odd number")


def check(input_num):
  try:
    num_int = int(input_num)
    print(f"Your type : {type(num_int)}")
    return 0

  except ValueError:
    print(f"Your type : {type(input_num)}")
    print("Your input is not a integer number")
    return 1

def number(number):
  ch = check(number)
  if ch == 0:
    num = int(number)
    check_number(num)
    check_even_odd(num)


number(num)