# -*- coding: utf-8 -*-
"""Activity 6_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IH-N4LrtrELZNT1g9w2ADWCWVgUczx-

# Activity 6.2: Discussion: Benefits of Modular Programming & Standard Library Exploration
Format: Class discussion or small group brainstorming.
Instructions:

1.Benefits of Modularity: Discuss scenarios where breaking code into functions and modules significantly helps (e.g., large projects, teamwork, debugging, code testing).

2.Standard Library Exploration: Provide a link to the official Python Standard Library documentation (docs.python.org/3/library/). Ask students to explore 2-3 modules they find interesting (e.g., datetime, os, sys, collections) and share a brief example of what they could use them for.

Purpose: Broaden understanding of Python's ecosystem, encourage independent exploration, and emphasize the importance of using existing tools.

###1.ตอบ  โดยการแบ่งโค้ดเป็น Module หรือ Function นั้นมีประโยชน์อย่างมากในหลายสถานการณ์ ตัวอย่างสถานการณ์เช่น เมื่อเราทำโปรเจคใหญ่ๆ ที่มีการรันโค้ดจำนวนมาก และส่วนใหญ่ก็มีการทำงานซ้ำๆ เราสามารถใช้ Function เพื่อช่วยจัดระเบียบโค้ดให้ดูสะอาดตา อ่านง่าย และช่วยลดจำนวนบรรทัดที่ต้องเขียนโค้ดที่ทำงานซ้ำๆ
-
-
-
-





###2.ตอบ
###1)warnings — Warning control : โมดูล warnings ใช้สำหรับแสดงและควบคุมข้อความแจ้งเตือนในโปรแกรม Python ซึ่งมีประโยชน์ในการแจ้งให้ผู้ใช้ทราบถึงปัญหาที่อาจเกิดขึ้นได้โดยไม่ต้องหยุดการทำงานของโปรแกรม  
###2)pdb — The Python Debugger : โมดูล pdb นี้กำหนดเครื่องมือดีบักโค้ดแบบโต้ตอบสำหรับโปรแกรม Python โดยรองรับการตั้งเบรกพอยต์ (แบบมีเงื่อนไข) และการก้าวทีละขั้นที่ระดับบรรทัดโค้ด การตรวจสอบเฟรมสแต็ก การแสดงรายการโค้ด และการประเมินโค้ด Python ใดๆ ในบริบทของเฟรมสแต็กใดๆ นอกจากนี้ยังรองรับการดีบักหลังเกิดข้อผิดพลาด และสามารถเรียกใช้งานได้ภายใต้การควบคุมของโปรแกรม
###3)http.cookiejar — Cookie handling for HTTP clients : โมดูล นี้http.cookiejarกำหนดคลาสสำหรับการจัดการคุกกี้ HTTP โดยอัตโนมัติ มีประโยชน์สำหรับการเข้าถึงเว็บไซต์ที่ต้องการข้อมูลขนาดเล็ก – คุกกี้ – ซึ่งจะต้องถูกตั้งค่าบนเครื่องไคลเอ็นต์โดยการตอบสนอง HTTP จากเว็บเซิร์ฟเวอร์ แล้วส่งกลับไปยังเซิร์ฟเวอร์ในการร้องขอ HTTP ครั้งต่อๆ ไป
"""