# -*- coding: utf-8 -*-
"""lab6_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXWm0AQyWG3K007whZqSOvTDLKSlTSb_

#Lab 6.1: Simple Calculator Functions
"""

def add(a , b):
  print(f"{a} + {b} = {a+b}")
  return a+b
def subtract(a,b):
  print(f"{a} - {b} = {a-b}")
  return a-b
def multiply(a,b):
  print(f"{a} * {b} = {a*b}")
  return a*b
def divide(a,b):
  if b == 0:
    print("Cannot divide by zero")
    return
  print(f"{a} / {b} = {a/b}")
  return a/b


while True:
  print("Menu\n1. add\n2. subtract\n3. multiply\n4. divide\n5. exit")
  choice = int(input("Enter your choice: "))
  if choice == 1:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))
    add(a,b)
  elif choice == 2:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))
    subtract(a,b)
  elif choice == 3:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))
    multiply(a,b)
  elif choice == 4:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))
    divide(a,b)
  elif choice == 5:
    break
  else:
    print("Invalid choice")

"""# Challenge Lab 6.1: Simple Calculator Functions"""

def add(a , b):
  """ส่งคืนผลบวกของสองจำนวน"""
  print(f"{a} + {b} = {a+b}")
  return a+b
def subtract(a,b):
  """ส่งคืนผลลบของสองจำนวน"""
  print(f"{a} - {b} = {a-b}")
  return a-b
def multiply(a,b):
  """ส่งคืนผลคูณของสองจำนวน"""
  print(f"{a} * {b} = {a*b}")
  return a*b
def divide(a,b):
  """ส่งคืนผลหารของสองจำนวน หรือคืนค่า Error เมื่อตัวหารเป็น 0"""
  if b == 0:
    print("Cannot divide by zero")
    return "Error: Division by zero"
  print(f"{a} / {b} = {a/b}")
  return a/b
def power(a,b=2):
  """ส่งคืนผลยกกำลัง โดยมีค่าเริ่มต้น b=2"""
  print(f"{a} ^ {b} = {a**b}")
  return a**b



while True:
  print("Menu\n1. add\n2. subtract\n3. multiply\n4. divide\n5. power\n6. exit")
  choice = int(input("Enter your choice: "))
  if choice == 1:
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    add(a,b)
  elif choice == 2:
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    subtract(a,b)
  elif choice == 3:
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    multiply(a,b)
  elif choice == 4:
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    divide(a,b)
  elif choice == 5:
      a = float(input("Enter first number: "))
      b = input("Enter second number: ")
      if b.strip() == "":
        power(a)
      else:
       power(a,float(b))
  elif choice == 6:
    break
  else:
    print("Invalid choice")