# -*- coding: utf-8 -*-
"""lab6_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAqppRa2gu0DAY4GqrFvQiAB_wayxl9j

# Lab 6.2: Custom Module and Standard Library Usage
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile my_utils.py
# 
# def greet(name):
#     print(f"Hello, {name}!")
# 
# 
# def is_prime(number):
#     if number < 2:
#         return False
# 
#     for i in range(2, number):
#         if number % i == 0:
#             return False
# 
#     return True

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main_program.py
# 
# import my_utils
# import math
# import random
# 
# my_utils.greet("Alice")
# 
# print("Is 7 prime?", my_utils.is_prime(7))
# print("Is 10 prime?", my_utils.is_prime(10))
# 
# print("Square root of 25 =", math.sqrt(25))
# 
# random_number = random.randint(1, 100)
# print("Random number =", random_number)