# -*- coding: utf-8 -*-
"""Activity 4.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_n35HkYOymKP3JV8kKDPeJwtVL9vucV

#Activity 4.2: Interactive To-Do List (using List Operations)
สิ่งที่อยากให้ทำ : ให้นักเรียนพัฒนาโปรแกรมจัดการรายการสิ่งที่ต้องทำ (To-Do List) แบบข้อความ (Text-based) อย่างง่าย โดยประยุกต์ใช้ความรู้เรื่องการจัดการ List ที่ได้เรียนมา
สิ่งที่ต้องมี

1. สร้าง List ว่างเริ่มต้นไว้ตัวหนึ่ง ชื่อว่า todo_list

2. ใช้การวนลูป while เพื่อแสดงเมนูคำสั่งให้ผู้ใช้เลือก ดังนี้:
2.1 เพิ่มรายการงาน (Add a task)
2.2 ดูรายการงานทั้งหมด (View tasks)
2.3 ทำเครื่องหมายว่างานเสร็จสิ้นแล้ว (ลบงานออก โดยเลือกจากตำแหน่ง Index หรือตามชื่อคำสั่ง)
2.4 ออกจากโปรแกรม (Exit)

3. ใช้คำสั่ง input() เพื่อรับค่าเมนูที่ผู้ใช้เลือก

4. ใช้คำสั่งจัดการ List ต่างๆ (เช่น append(), remove() หรือ pop(), len()) ในการบริหารจัดการข้อมูลใน todo_list
"""

todo_list = []
while True:
  print("\nMenu\n1. Add a task\n2. View tasks\n3.Mark the task as complete.\n4. Exit\n")
  try:
    number = int(input("Input your number : "))
  except ValueError:
    print("Please enter a number")
    continue
  if number ==1:
    print("\n1) Add a task")
    try:
      count_task_add = int(input("Input Number of task : "))
    except ValueError:
      print("Please enter a number")
      continue
    for i in range(count_task_add):
        task = input(f"Enter task name #{i + 1}: ")
        todo_list.append(task)
  elif number == 2:
    print("2) View tasks")
    for i in todo_list:
      print(i)
  elif number == 3:
    print("\n3)Mark the task as complete\nSelect a method to delete the task\n1. Select from the index\n2. Select from task titles")
    try:
     num= int(input("Input your number : "))
    except ValueError:
     print("Please enter a number")
     continue
    if num == 1:
      try:
        index = int(input("Input your index : "))
        todo_list.remove(todo_list[index])
      except IndexError:
        print("Invalid index")
      except ValueError:
        print("Please enter a number")
    elif num == 2:
      try:
          task_titles = input("Input your task : ")
          todo_list.remove(task_titles)
      except ValueError:
          print("Task not found")
    else:
      print("Please Input Your Correct Number\n")
  elif number == 4:
    print("Thank you !")
    break
  else:
    print("Please Input Your Correct Number\n")

