# -*- coding: utf-8 -*-
"""lab4_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcg8GsgwQDcYMJWh2k-1P2Y5JcD0jgOt

# LAB 4.1: Student Management System (List Operations)
"""

student_names = []
print("\n[1] Add Students")
count_Student_add = int(input("Input Number of Students : "))
for i in range(count_Student_add):
    student = input(f"Enter student name #{i + 1}: ")
    student_names.append(student)

print(f"Current list: {student_names}")

print("\n[2] Find a Student")
search_name = input("Enter a name to search for: ")

if search_name in student_names:
    position = student_names.index(search_name)
    print(f"Found '{search_name}' at index {position}")
else:
    print(f"'{search_name}' not found in the list")

print("\n[3] Remove a Student")
remove_name = input("Enter a name to remove: ")

if remove_name in student_names:
    student_names.remove(remove_name)
    print(f"'{remove_name}' has been removed")
else:
    print(f"'{remove_name}' not found, nothing removed")

print(f"Updated list: {student_names}")

print("\n[4] Sort Students")
student_names.sort()
print(f"Sorted list: {student_names}")

print("\n[5] Count Students")
print(f"Total students: {len(student_names)}")

"""#Challenge LAB 4.1


"""

student_names = []
while True:
  print("Menu\n1. Add Students\n2. Remove a Student\n3. Find a Student\n4. Sort Students\n5. Count Students\n6. Exit\n")
  number = int(input("Please Choose Your Menu: "))

  if number == 1:
    print("\n[1] Add Students")
    count_Student_add = int(input("Input Number of Students : "))
    for i in range(count_Student_add):
        student = input(f"Enter student name #{i + 1}: ")
        student_names.append(student)

    print(f"Current list: {student_names}")
  elif number == 2:
    print("\n[2] Remove a Student")
    remove_name = input("Enter a name to remove: ")

    if remove_name in student_names:
        student_names.remove(remove_name)
        print(f"'{remove_name}' has been removed")
    else:
        print(f"'{remove_name}' not found, nothing removed")

    print(f"Updated list: {student_names}")

  elif number == 3:
    print("\n[3] Find a Student")
    search_name = input("Enter a name to search for: ")

    if search_name in student_names:
        position = student_names.index(search_name)
        print(f"Found '{search_name}' at index {position}")
    else:
        print(f"'{search_name}' not found in the list")

  elif number == 4:
    print("\n[4] Sort Students")
    student_names.sort()
    print(f"Sorted list: {student_names}")

  elif number == 5:
    print("\n[5] Count Students")
    print(f"Total students: {len(student_names)}")
  elif number == 6:
    print("Thank You!")
    break
  else:
    print("Please Input Your Correct Number \n")