# -*- coding: utf-8 -*-
"""lab4_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xor7RTO1ftYGw1uXQP9ubBpu60Bx0qFJ

# Lab 4.2: Geometric Calculations (Tuples & Immutability)
"""

import math
point1 = (3, 4)
point2 = (6, 8)

print("\n[1] Access Coordinates")
print(f"Point 1: x = {point1[0]}, y = {point1[1]}")
print(f"Point 2: x = {point2[0]}, y = {point2[1]}")

print("\n[2] Attempt Modification (Immutability Demonstration)")
try:
    point1[0] = 5  # บรรทัดนี้จะทำให้เกิด TypeError เพราะ tuple แก้ไขไม่ได้
except TypeError as e:
    print(f"Error trying to modify tuple: {e}")

#   distance = sqrt( (x2 - x1)^2 + (y2 - y1)^2 )
print("\n[3] Calculate Distance")
distance = math.sqrt((point2[0] - point1[0]) ** 2 + (point2[1] - point1[1]) ** 2)
print(f"Distance between point1 {point1} and point2 {point2}: {distance}")

"""# Challenge LAB 4.2"""

import math
x1 = float(input("Input x for point1 :"))
y1 = float(input("Input y for point1 :"))
x2 = float(input("Input x for point2 :"))
y2 = float(input("Input y for point2 :"))
point1 = (x1, y1)
point2 = (x2, y2)

print("\n[1] Access Coordinates")
print(f"Point 1: x = {point1[0]}, y = {point1[1]}")
print(f"Point 2: x = {point2[0]}, y = {point2[1]}")

print("\n[2] Attempt Modification (Immutability Demonstration)")
try:
    point1[0] = 5  # บรรทัดนี้จะทำให้เกิด TypeError เพราะ tuple แก้ไขไม่ได้
except TypeError as e:
    print(f"Error trying to modify tuple: {e}")

#   distance = sqrt( (x2 - x1)^2 + (y2 - y1)^2 )
print("\n[3] Calculate Distance")
distance = math.sqrt((point2[0] - point1[0]) ** 2 + (point2[1] - point1[1]) ** 2)
print(f"Distance between point1 {point1} and point2 {point2}: {distance}")